import { useEffect, useRef, useState } from 'react'
import { Activity, Radio, CheckCircle2, XCircle, Clock3, Info } from 'lucide-react'
import { useLiveStatus } from '../hooks/useApi'

function formatAge(ts?: number) {
  if (!ts) return 'never'
  const seconds = Math.max(0, Math.floor((Date.now() - ts) / 1000))
  if (seconds < 60) return `${seconds}s ago`
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes}m ago`
  const hours = Math.floor(minutes / 60)
  return `${hours}h ago`
}

function Hint({ text }: { text: string }) {
  const [open, setOpen] = useState(false)
  const timerRef = useRef<number | null>(null)

  function openWithDelay() {
    if (timerRef.current) window.clearTimeout(timerRef.current)
    timerRef.current = window.setTimeout(() => setOpen(true), 320)
  }

  function closeNow() {
    if (timerRef.current) {
      window.clearTimeout(timerRef.current)
      timerRef.current = null
    }
    setOpen(false)
  }

  useEffect(() => {
    return () => {
      if (timerRef.current) {
        window.clearTimeout(timerRef.current)
      }
    }
  }, [])

  return (
    <span
      className="relative inline-flex items-center text-pulse-muted/80"
      onMouseEnter={openWithDelay}
      onMouseLeave={closeNow}
      onFocus={openWithDelay}
      onBlur={closeNow}
      tabIndex={0}
      aria-label={text}
    >
      <Info className="w-3 h-3 cursor-help" />
      {open && (
        <span className="absolute z-10 left-1/2 -translate-x-1/2 top-full mt-1.5 w-48 rounded-md border border-pulse-border bg-pulse-bg px-2 py-1.5 text-[10px] leading-snug text-pulse-text shadow-lg">
          {text}
        </span>
      )}
    </span>
  )
}

function MetricCard({ label, value, hint }: { label: string; value: string | number; hint: string }) {
  return (
    <div className="rounded-lg border border-pulse-border bg-pulse-bg/40 p-2.5">
      <div className="flex items-center gap-1 text-[11px] text-pulse-muted">
        <span>{label}</span>
        <Hint text={hint} />
      </div>
      <p className="text-sm font-semibold text-white mt-0.5">{value}</p>
    </div>
  )
}

export default function LiveEngineStatus() {
  const { data } = useLiveStatus()
  const status = data?.status

  if (!status) {
    return null
  }

  const isLive = status.runtimeMode === 'live'
  const connected = Boolean(status.connected)

  const badgeText = isLive
    ? (connected ? 'Live Stream' : 'Reconnecting')
    : 'Simulated Stream'

  const badgeClass = isLive
    ? (connected
      ? 'bg-pulse-accent/10 text-pulse-accent border-pulse-accent/30'
      : 'bg-white/5 text-pulse-muted border-pulse-border')
    : 'bg-blue-400/10 text-blue-300 border-blue-400/30'

  const flowLabel = isLive ? 'Tracked Matches' : 'Simulated Exits'
  const flowValue = isLive ? status.trackedWalletMatches : status.demoExecutions
  const flowHint = isLive
    ? 'Tracked-wallet exits that matched your watchlist tokens.'
    : 'Demo approvals/exits successfully simulated during this session.'

  return (
    <div className="glass-card p-4 sm:p-5">
      <div className="flex items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2">
          <Activity className="w-4 h-4 text-blue-400" />
          <h3 className="text-white text-sm sm:text-base font-bold">Stream Status</h3>
        </div>

        <span className={`inline-flex items-center gap-1.5 text-[11px] px-2 py-1 rounded-full border font-semibold ${badgeClass}`}>
          <Radio className="w-3 h-3" />
          {badgeText}
        </span>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-3">
        <MetricCard
          label="Mode"
          value={String(status.runtimeMode).toUpperCase()}
          hint="Current runtime mode of the signal engine."
        />
        <MetricCard
          label="Watchlist Tokens"
          value={status.watchlistCount}
          hint="How many token positions are currently monitored for smart-wallet exits."
        />
        <MetricCard
          label={flowLabel}
          value={flowValue}
          hint={flowHint}
        />
        <MetricCard
          label="Signals Generated"
          value={status.signalsEmitted}
          hint="Total consensus alerts generated by the engine in this session."
        />
      </div>

      <div className="flex flex-wrap items-center gap-3 text-[11px] text-pulse-muted">
        <span className="inline-flex items-center gap-1">
          <Clock3 className="w-3.5 h-3.5" />
          Last stream update: {formatAge(status.lastMessageAt)}
        </span>
        <span className="inline-flex items-center gap-1">
          <Clock3 className="w-3.5 h-3.5" />
          Last {isLive ? 'tracked-wallet match' : 'simulated execution'}: {formatAge(status.lastExitAt)}
        </span>
      </div>

      <div className="mt-3 rounded-lg border border-pulse-border bg-pulse-bg/40 p-2.5 text-xs text-pulse-muted">
        {isLive ? (
          connected ? (
            status.watchlistCount > 0
              ? (
                <span className="inline-flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-pulse-accent" />
                  Live stream is active and evaluating exits for your tracked holdings.
                </span>
                )
              : (
                <span className="inline-flex items-center gap-1.5">
                  <XCircle className="w-3.5 h-3.5 text-pulse-warning" />
                  Live stream is connected, but no tokens are in your watchlist yet.
                </span>
                )
          ) : (
            <span className="inline-flex items-center gap-1.5">
              <XCircle className="w-3.5 h-3.5 text-pulse-danger" />
              Live mode is on. Reconnecting to the Ave data stream.
            </span>
          )
        ) : (
          <span className="inline-flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-blue-400" />
            Demo mode is on. Signals and stream activity are simulated for product walkthrough.
          </span>
        )}
      </div>

      {status.lastError && isLive && (
        <p className="mt-2 text-[11px] text-pulse-warning">
          Stream note: {status.lastError}
        </p>
      )}
    </div>
  )
}
